### ISSUE TITLE
Help integrating this WebSocket server with lb4 app

### ISSUE THREAD

**Issue by bobseekone** [raymondfeng/loopback4-example-websocket#3]
I have been trying to integrate this example into a simple Loopback 4 application. For example, I did:

#lb4 app test

which generated a simple app with just a /ping endpoint. I would like to add a  WebSocketServer to it, but the constructor requires passing in an HttpServer. I am not sure how to get access to the HttpServer from the lb4 application. Any help integrating this would be much appreciated!

**Comment by raymondfeng** [comment]
We have some work in progress here - https://github.com/strongloop/loopback-next/tree/socketio/packages/socketio

**Comment by bobseekone** [comment]
Thank you Raymond. I have installed socketio using your instructions in your post on April 19. Is there some example code of how to use it anywhere?
